### ISSUE TITLE
API needs ordering parameters

### ISSUE THREAD

**Issue by chadmiller** [jamesturk/tot#122]
Returned elements from API calls are not in any useful order. We should be able to specify a key/direction pair, or pairs to get results by.

**Comment by chadmiller** [comment]
@toxicbakery. ^

**Comment by ToxicBakery** [comment]
@chadmiller Testing seems good on the above, can you glance at that and validate I did not miss anything important? I'm not sure how to pass multiple columns from the query to the order_by method but I imagine if the query was order_by=[name,date] there is an easy python way to take that array and give it to the method. Any pointers are welcome :+1:

**Comment by ToxicBakery** [comment]
Incorporates your commentary minus the `tuple` reference. I didn't understand what that accomplished and testing the implementation without tuple, the results seem to be what was expected using two and three parameters of `order_by` input.

**Comment by jamesturk** [comment]
sorry for the delay on this, there's actually sorting built into the JSON API framework being used, but it had just been temporarily disabled due to performance concerns earlier, I forgot it hadn't been turned back on though

I've turned it back on, it works as documented here: http://jsonapi.org/format/#fetching-sorting
